POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "Fahmi",
    "password": "12345"
}

###

POST http://localhost:3000/viewVisitor
Content-Type: application/json

{
    "name": "Fahmi",
    "password": "12345",
    "role": "admin"
}

###

POST http://localhost:3000/registerVisitor
Content-Type: application/json

{
    "role": "visitor",
    "name": "Wong Siew",
    "idNumber": "444555666",
    "documentType": "Passport",
    "gender": "Male",
    "birthDate": "2006-03-12",
    "age": "29",
    "documentExpiry": "2033-09-23", 
    "company": "sambal",
    "TelephoneNumber": "029572756",
    "vehicleNumber": "jvj123",
    "category": "Relatives",
    "ethnicity": "Chinese",
    "photoAttributes": "Photo attributes here",
    "passNumber": "004"
}

###

POST  http://localhost:3000/changePhoneNumber
Content-Type: application/json

{
    "savedidNumber": "20223112",
    "newphoneNumber": "0169042665"
}

###

POST http://localhost:3000/deleteVisitor
Content-Type: application/json

{
    "name": "Arif Saiful",
    "idNumber": "111222333"
}